version: '3.4'

services:

  sqldata:
    environment:
      - MSSQL_SA_PASSWORD=Strong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - 5433:1433
    volumes:
      - ./vol/sqlserver/data:/var/opt/mssql/data

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - acd_rabbitmq_data:/home/rabbitmq/data

  jaeger:
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: true

  seq:
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - acd_seq_data:/home/seq/data

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "51231:8080"
      - "51232:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
